### ISSUE TITLE
Question: presenters

### ISSUE THREAD

**Issue by TomasNiemczyk98** [3PillarGlobal-Ostrava/interview-app-api#22]
@petrspelos 
How should we handle presenters in our application?
See #11 for more details please

**Comment by PlesnikJakub** [comment]
@petrspelos

**Comment by petrspelos** [comment]
Default implementation isn't needed, we can use mocks in our tests. ☺️

**Comment by PlesnikJakub** [comment]
@TomasNiemczyk98 please update your latest PR based on this.
